### ISSUE TITLE
Automations set temp to lowest & fan to highest

### ISSUE THREAD

**Issue by grork** [nitaybz/homebridge-tado-ac#71] opened 2019-03-17 16:32 UTC
When using 3.1.2, HomeKit automations do not correctly set the desired temperature.
My configuration is _default_, I have only provided the required fields (password etc).

**Problematic Behaviour:**
When using a HomeKit automation to turn my tado on at a specific time, the plugin sets my Tado to 61f/HEAT/Full Fan. The settings in HomeKit for the automation set 75f/heat/Auto Fan. Of note:
- I tried recreating the automation multiple times
- It worked fine with plugin 2.x
- I have a Sensibo Sky + Homebridge Plugin, which works fine in an automation.
- HomeKit seems to display the intended configuration at first, and then updates to the 61f target temp a few seconds later

Logs below!

_Of Note_:
- With on/off behaviour manually initiated, the previous state of the device (E.g. fan/temp) is restored
- Off works fine too!
- Manual control is fine; I can set the temperature etc.

_Logs_
Starting from an off state, I ran the automation. Here are the logs:
````
[2019-3-17 16:15:17] [TadoAC] Fireplace Mode is  OFF[20/1839]
[2019-3-17 16:15:17] [TadoAC] Fireplace Rotation Speed - Device is OFF
[2019-3-17 16:15:17] [TadoAC] Fireplace Current Temperature is 68.41ºF
[2019-3-17 16:15:17] [TadoAC] Fireplace Active State is 0
[2019-3-17 16:15:17] [TadoAC] Fireplace Target State is  OFF
[2019-3-17 16:15:30] [TadoAC] Fireplace -> Setting state Active: power ON
[2019-3-17 16:15:30] [TadoAC] Fireplace -> Setting Rotation Speed: fanspeed HIGH
[2019-3-17 16:15:30] [TadoAC] Fireplace -> Setting Target HeaterCooler State: mode HEAT
[2019-3-17 16:15:30] [TadoAC] Fireplace -> Setting Target Temperature: temp 24
[2019-3-17 16:15:30] [TadoAC] Fireplace -> Setting Target Temperature: temp 16
[2019-3-17 16:15:30] [TadoAC] Lounge -> Setting state Active: power ON
[2019-3-17 16:15:30] [TadoAC] Lounge -> Setting Target HeaterCooler State: mode HEAT
[2019-3-17 16:15:30] [TadoAC] Lounge -> Setting Target Temperature: temp 24
[2019-3-17 16:15:30] [TadoAC] Lounge -> Setting Target Temperature: temp 16
[2019-3-17 16:15:30] [TadoAC] Lounge -> Setting Rotation Speed: fanspeed HIGH
[2019-3-17 16:15:30] [TadoAC] Setting new state on Fireplace -->
[2019-3-17 16:15:30] [TadoAC] { termination: { type: 'MANUAL' },
  setting:
   { power: 'ON',
     type: 'AIR_CONDITIONING',
     mode: 'HEAT',
     temperature: { celsius: 16, fahrenheit: 61 },
     fanSpeed: 'HIGH' } }
[2019-3-17 16:15:30] [TadoAC] Setting new state on Lounge -->
[2019-3-17 16:15:30] [TadoAC] { termination: { type: 'MANUAL' },
  setting:
   { power: 'ON',
     type: 'AIR_CONDITIONING',
     mode: 'HEAT',
     temperature: { celsius: 16, fahrenheit: 61 },
     fanSpeed: 'HIGH' } }
setOverlay response: { type: 'MANUAL',
  setting:
   { type: 'AIR_CONDITIONING',
     power: 'ON',
     mode: 'HEAT',
     temperature: { celsius: 16.11, fahrenheit: 61 },
     fanSpeed: 'HIGH' },
  termination:
   { type: 'MANUAL',
     typeSkillBasedApp: 'MANUAL',
     projectedExpiry: null } }
2019-3-17 16:15:31] [TadoAC] Updating Accessory for Fireplace Tado
[2019-3-17 16:15:31] [TadoAC] Fireplace Tado *New State* - Mode - HEAT
[2019-3-17 16:15:31] [TadoAC] Fireplace Tado *New State* - Fan Speed - HIGH
[2019-3-17 16:15:31] [TadoAC] Fireplace Tado *New State* - Heating Threshold Temperature - 61 ºF
setOverlay response: { type: 'MANUAL',
  setting:
   { type: 'AIR_CONDITIONING',
     power: 'ON',
     mode: 'HEAT',
     temperature: { celsius: 16.11, fahrenheit: 61 },
     fanSpeed: 'HIGH' },
  termination:
   { type: 'MANUAL',
     typeSkillBasedApp: 'MANUAL',
     projectedExpiry: null } }
[2019-3-17 16:15:31] [TadoAC] Updating Accessory for Lounge Tado
[2019-3-17 16:15:31] [TadoAC] Lounge Tado *New State* - Mode - HEAT
[2019-3-17 16:15:31] [TadoAC] Lounge Tado *New State* - Fan Speed - HIGH
[2019-3-17 16:15:31] [TadoAC] Lounge Tado *New State* - Heating Threshold Temperature - 61 ºF
````

**Comment by nitaybz** [comment] 2019-10-06 10:16
Please try the latest version (3.2)... it should solve this issue

**Comment by nitaybz** [comment] 2019-11-26 14:12
closing since there is no comment and the issue is probably fixed

**Closed as completed by nitaybz** 2019-11-26 14:12 UTC
