### ISSUE TITLE
Tado requests do not retry periodically as logs indicate

### ISSUE THREAD

**Issue by ghost** [nitaybz/homebridge-tado-ac#63] opened 2019-01-16 03:30 UTC
If Homebridge starts the Tado plugin without an active internet connection (common for boot process), it appears that the initialisation fails and will not recover. You'll notice just after the first failure, a log item says "...trying again in 10 seconds", but it doesn't appear that this happens.

The full output is as follows:

> Jan 16 13:41:06 raspberrypi homebridge[296]: [1/16/2019, 1:41:06 PM] Loaded config.json with 0 accessories and 1 platforms.
Jan 16 13:41:06 raspberrypi homebridge[296]: [1/16/2019, 1:41:06 PM] ---
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] Loaded plugin: homebridge-tado-ac
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] Registering platform 'homebridge-tado-ac.TadoAC'
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] ---
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] Loading 1 platforms...
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] [Tado AC] Initializing TadoAC platform...
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] Loading 0 accessories...
Jan 16 13:41:07 raspberrypi homebridge[296]: { Error: getaddrinfo EAI_AGAIN auth.tado.com auth.tado.com:443
Jan 16 13:41:07 raspberrypi homebridge[296]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Jan 16 13:41:07 raspberrypi homebridge[296]:   errno: 'EAI_AGAIN',
Jan 16 13:41:07 raspberrypi homebridge[296]:   code: 'EAI_AGAIN',
Jan 16 13:41:07 raspberrypi homebridge[296]:   syscall: 'getaddrinfo',
Jan 16 13:41:07 raspberrypi homebridge[296]:   hostname: 'auth.tado.com',
Jan 16 13:41:07 raspberrypi homebridge[296]:   host: 'auth.tado.com',
Jan 16 13:41:07 raspberrypi homebridge[296]:   port: 443 }
Jan 16 13:41:07 raspberrypi homebridge[296]: Couldn't Get Tado Token! trying again in 10 seconds
Jan 16 13:41:07 raspberrypi homebridge[296]: { Error: getaddrinfo EAI_AGAIN my.tado.com my.tado.com:443
Jan 16 13:41:07 raspberrypi homebridge[296]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Jan 16 13:41:07 raspberrypi homebridge[296]:   errno: 'EAI_AGAIN',
Jan 16 13:41:07 raspberrypi homebridge[296]:   code: 'EAI_AGAIN',
Jan 16 13:41:07 raspberrypi homebridge[296]:   syscall: 'getaddrinfo',
Jan 16 13:41:07 raspberrypi homebridge[296]:   hostname: 'my.tado.com',
Jan 16 13:41:07 raspberrypi homebridge[296]:   host: 'my.tado.com',
Jan 16 13:41:07 raspberrypi homebridge[296]:   port: 443 }
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] [Tado AC] XXX - Error Getting Temperature Unit - XXX
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] [Tado AC] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] [Tado AC] Can't finish Tado Installation
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] [Tado AC] Please check you config and restart homebridge
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] [Tado AC] If the problem persist, plese open Issue at https://github.com/nitaybz/homebridge-tado-ac/issues
Jan 16 13:41:07 raspberrypi homebridge[296]: [1/16/2019, 1:41:07 PM] [Tado AC] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by nitaybz** [comment] 2019-10-06 10:15
Please try the latest version (3.2)... it should solve this issue

**Comment by nitaybz** [comment] 2019-11-26 14:11
closing since there is no comment and the issue is probably fixed

**Closed as completed by nitaybz** 2019-11-26 14:11 UTC
