### ISSUE TITLE
again token problems and homebridge crash ??

### ISSUE THREAD

**Issue by roe1974** [nitaybz/homebridge-tado-ac#67] opened 2019-02-11 10:30 UTC
here the log
`Feb 11 11:26:25 homebridge-raspi homebridge[11498]: SyntaxError: Unexpected token < in JSON at position 0
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at JSON.parse (<anonymous>)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at IncomingMessage.res.on (/usr/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:20:34)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at emitNone (events.js:111:20)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at IncomingMessage.emit (events.js:208:7)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at endReadableNT (_stream_readable.js:1064:12)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: Couldn't Parse strData:
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: <html>
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: <head><title>502 Bad Gateway</title></head>
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: <body bgcolor="white">
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: <center><h1>502 Bad Gateway</h1></center>
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: </body>
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: </html>
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: undefined:1
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: <html>
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: ^
Feb 11 11:26:25 homebridge-raspi homebridge[11498]: SyntaxError: Unexpected token < in JSON at position 0
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at JSON.parse (<anonymous>)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at IncomingMessage.res.on (/usr/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:27:26)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at emitNone (events.js:111:20)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at IncomingMessage.emit (events.js:208:7)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at endReadableNT (_stream_readable.js:1064:12)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
Feb 11 11:26:25 homebridge-raspi homebridge[11498]:     at process._tickCallback (internal/process/next_tick.js:181:9)
`

**Comment by matthieulrg** [comment] 2019-04-09 07:37
Hi,

I'm having the exact same issue since months... Homebridge is shutting down every time. Here's the log : 

`[2019-4-8 10:17:09] [Tado AC] Turning OFF Chambre AC
[2019-4-8 14:14:53] [Tado AC] couldn't retrieve new Token, error:SyntaxError: Unexpected token < in JSON at position 0
Fetching Token failed - Trying again...
[2019-4-8 14:14:53] Got SIGTERM, shutting down Homebridge...`

**Comment by nitaybz** [comment] 2019-10-06 10:15
Please try the latest version (3.2)... it should solve this issue

**Comment by nitaybz** [comment] 2019-11-26 14:12
closing since there is no comment and the issue is probably fixed

**Closed as completed by nitaybz** 2019-11-26 14:12 UTC
