### ISSUE TITLE
bug geolocalisation

### ISSUE THREAD

**Issue by jeyf** [nitaybz/homebridge-tado-ac#97] opened 2020-10-08 15:17 UTC
when i go to off mode , tje tado app goes to off mode but "at home" not in auto geoloc" mode

and i can't make disappear the fan switch in homekit app

"platform": "TadoAC",
            "name": "Tado AC",
            "username": "xxxxxxxxxx",
            "password": "xxxxxxxx",
            "tadoMode": "TADO_MODE",
            "autoFanOnly": true,
            "desableFan": true,
            "statePollingInterval": 10,
            "anyoneSensor": true

**Comment by nitaybz** [comment] 2020-10-09 20:09
You have a type to remove the fan. It should be
"disableFan".

I'll release a new version pretty soon.
Refactoring the entire code. Hope it will solve your other issue.

**Comment by nitaybz** [comment] 2020-10-17 19:10
Should be fixed in version 4 !

Hope you can approve that it works as expected

**Comment by jeyf** [comment] 2020-10-19 08:14
yess it seems to work perfectly !!!
but when on homekit i press the device who is off .. the device pass to auto AC mode 
it would perfect if the device not changed when we press on it .... 
i can change mode to heat or freeze but not to off ... 
"username": "xxxxxxxx",
            "password": "xxxxxxxx",
            "occupancySensorsEnabled": true,
            "occupancyPollingInterval": 10,
            "anyoneSensor": false,
            "weatherSensorsEnabled": false,
            "weatherPollingInterval": 5,
            "homeID": xxxxx,
            "tadoMode": "TADO_MODE",
            "durationInMinutes": 90,
            "disableFan": true,
            "disableDry": true,
            "manualControlSwitch": false,
            "historyStorage": false,
            "extraHumiditySensor": false,
            "forceThermostat": false,
            "forceHeaterCooler": false,
            "disableAcAccessory": false,
            "statePollingInterval": 10,
            "debug": false,
            "platform": "TadoAC"

**Comment by nitaybz** [comment] 2020-10-19 08:36
when you click on the device it will just pick the last mode you had...
There is no "OFF" mode for airconditioners in HomeKit (only for thermostats)... so not a bug

**Comment by jeyf** [comment] 2020-10-19 08:41
sorry when i click to the device who was off .. the device enable automatique Mode ... i can select heat , or freeze mode but when i select off mode it does not off the device

**Comment by nitaybz** [comment] 2020-10-19 08:57
can you share a screenshot? how do you select off mode?

**Comment by nitaybz** [comment] 2020-10-19 08:58
are you on Thermostatic Control?

**Comment by jeyf** [comment] 2020-10-19 09:07
when i click on device it change automatically like this  

![IMG_4937](https://user-images.githubusercontent.com/56220262/96424268-c59f9c00-11fa-11eb-863d-66adec67b39b.PNG)

and when  i change "AUTOM." to "ETEINT" like this 
![IMG_4938](https://user-images.githubusercontent.com/56220262/96424440-fe3f7580-11fa-11eb-95e9-59d3dab4019b.PNG)
it doesent off the split 

i have no thermostatic but TADO AC v2

**Comment by nitaybz** [comment] 2020-10-19 09:14
can you turn on "debug logs" in the plugin settings and send some logs?

**Comment by nitaybz** [comment] 2020-10-19 09:23
ok I think I've found the bug... please install version 4.0.9
let me know if that solves your issue

**Comment by jeyf** [comment] 2020-10-19 09:24
sorry too many logs on screen... but i try to select the good option "ETEINT" the press the grey power button at the bottom of screen then the gry button goes blue ... then i press a second time the blue power button and it works and goes off to tado i would prefer that the power button will be replace by "ETEINT" mode

**Comment by nitaybz** [comment] 2020-10-19 09:26
they grey power button is not related... probably part of other accessory... please scroll down in the accessory and click on "Show as separate tiles" to reveal all accessories

**Comment by jeyf** [comment] 2020-10-19 09:31
yessssss very good the 4.0.9 works very well !!!! 
best regards !!

**Comment by nitaybz** [comment] 2020-10-19 09:37
glad it worked :)

**Comment by jeyf** [comment] 2020-10-19 09:43
juste two  more things... 
 - the grey power button appears for dry mode..

 -when the tado is off by tado app in geoloc mode it is like this : 
![IMG_4939](https://user-images.githubusercontent.com/56220262/96428262-d8689f80-11ff-11eb-92ae-dba35a247593.PNG)

- when i said "allume le chauffage à 25 °C  dans le salon " the device works in auto mode ton 25°C it works but it would be perfect if it goes to heat mode not to auto and geoloc is in maison like this not geo mode
![IMG_4940](https://user-images.githubusercontent.com/56220262/96428313-eae2d900-11ff-11eb-997c-0f096842fb7a.PNG)

- when i said " eteint le chauffage dans le salon the tado app appears like this : 
![IMG_4941](https://user-images.githubusercontent.com/56220262/96428461-136ad300-1200-11eb-849d-0fb83c585ae2.PNG)

but it must be like this in geo mode... it was the original problem of the post 

![IMG_4939](https://user-images.githubusercontent.com/56220262/96428561-309fa180-1200-11eb-9ec4-80976e8c8472.PNG)

**Comment by nitaybz** [comment] 2020-10-19 10:11
ok so I see 2 topics here... I'll try to address each separately:

1. When you ask Siri to turn on the Heating at 25, it might not be accurate... because by Heating, she might think you are referring to the device and not to the mode... I'll try to play with it by saying it otherwise... maybe something like: Set the Salon to Heat, or Heat the Salon. or if Heat is already your last state used, you may even say something like: "set the salon to 25 degrees". there is no solution here from within the plugin but to find the right phrase Siri gets well

2. regarding your original question about the command mode, the "tadoMode" settings in the config is what controlling the command mode, but it's important to understand that every command you send from the Home app will be counted as "MANUAL" until an event that will be decided by the tado mode.
I think that the image you are showing in tado app when you turn it off, is actually the removal of the manual control. try adding the manual control switch in the plugin config and then turn that button off and let me know if it gets you where you want.

**Comment by jeyf** [comment] 2020-10-19 13:48
yes when i shutt off the manual control it works with normal geololc off mode like this

![IMG_4939](https://user-images.githubusercontent.com/56220262/96459371-59389300-1222-11eb-904d-04b9bd7a8208.PNG)

**Comment by nitaybz** [comment] 2020-10-19 14:23
so it's all intended... there is not way for you to turn OFF the device and get to this stage... it can only be done by turning off manual control

**Comment by jeyf** [comment] 2020-10-19 14:27
yes but id would be wonderfull if the manual control off would be mixed and integrated in the off device command

**Comment by nitaybz** [comment] 2020-10-19 18:47
That's not really making sense because some users have setup the AC to be ON in certain hours so when you'll actually click the off button it will turn it on or move it to the predefined state for this time of day

**Comment by nitaybz** [comment] 2020-10-20 09:00
can I close the issue? are we good here?

**Comment by jeyf** [comment] 2020-10-21 11:44
yes very good 
best regards

**Closed as completed** 2020-10-22 07:12 UTC
