### ISSUE TITLE
Only pulling the temperature for the given mode

### ISSUE THREAD

**Issue by jadomski** [nitaybz/homebridge-tado-ac#95] opened 2020-06-17 03:07 UTC
When in the HeaterCooler (AC) mode, the plugin will only grab the target temperature for the current mode. This means that when Homebridge is restarted, it forgets the temperature which the other modes have been set to.

As an example, if I set my heat target to 20 degrees and my cool target to 25 degrees, and my AC is currently in heating mode, when I restart the homebridge plugin it forgets the cool target mode. In some cases this prevents the temperature for the heat mode from being set until it has been manually set through the Tado or through a third party HomeKit app.

The issue does not present itself in thermostat mode.

**Comment by nitaybz** [comment] 2020-10-17 19:09
Should be fixed in version 4 !

Hope you can approve that it works as expected

**Comment by jadomski** [comment] 2020-10-17 23:28
I’ve upgraded the plug-in but it does not appear to be resolved.

After the upgrade there’s an additional power icon on the room page in the Home app - I’m not sure if this is related?

**Comment by nitaybz** [comment] 2020-10-18 06:41
what is the name of this power icon? I'll tell you if it's related.

I think I did not understand your issue quite well, but let me tell you about the plugin expected behaviour and how it is intended to be:
1. the plugin cache your last mode settings and will always use it for the next mode.
2. when you change mode, temperature, fan speed or swing the plugin will take the last state you had and replace that change.

Example: 
1. Current mode: "COOL 24° high fanspeed and swing ON"
2. You make a change to HEAT. the command will be sent with the following: "HEAT 24° high fanspeed and swing ON"
3. it is not intended to keep the last HEAT temperature, it is assumed that users are not switching between heat and cool too often as those are meant for different seasons mostly.

hope it clear things out

**Comment by nitaybz** [comment] 2020-10-18 06:54
if this still persist let me know:
> In some cases this prevents the temperature for the heat mode from being set until it has been manually set through the Tado or through a third party HomeKit app.

**Comment by jadomski** [comment] 2020-10-19 03:00
Ah gotcha, in that case it is working correctly and appears to be caching the temperature per your explanation.

Regarding the extra power icon, I think it’s related to the dry setting but not sure why it’s coming up in the way it is. I’ve attached a screenshot.

![E1D302C4-C528-4148-83E4-415784A47E37](https://user-images.githubusercontent.com/7396502/96396677-76199a00-1213-11eb-8dcb-3a52350a10d0.jpeg)

**Comment by nitaybz** [comment] 2020-10-19 06:48
this is not a bug in the plugin... just the stupid way apple did the grouping... I suggest just to show them as separate tiles...
scroll down to the accessory settings and click "Show as separate tiles"

**Comment by jadomski** [comment] 2020-10-19 07:50
I'm guessing this means there's currently no way to show HEAT/COOL/FAN/OFF in the scrollable picker?

Happy to close this ticket by the way 👍  Thanks again for the great work you do with this plugin!

**Comment by nitaybz** [comment] 2020-10-19 07:58
yeah I wish there was a way! I'm always on top of HomeKit protocol improvements so if something will come up I'll sure update the plugin.

Thanks

**Closed as completed by nitaybz** 2020-10-19 07:58 UTC
Labels: solution is on the way
