### ISSUE TITLE
New crash error 503

### ISSUE THREAD

**Issue by jetmcquack** [nitaybz/homebridge-tado-ac#73] opened 2019-04-11 13:48 UTC
recently Tado-AC started crashing, i think because of some changes on Tado Side.

the error i get is

```
SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.res.on.e (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:20:34)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Couldn't Parse strData:
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>

undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.res.on.e (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:27:26)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

and then home bridge crashes and needs to be restarted

**Comment by roe1974** [comment] 2019-06-26 09:09
same here......

**Comment by nitaybz** [comment] 2019-10-06 10:16
Please try the latest version (3.2)... it should solve this issue

**Comment by nitaybz** [comment] 2019-11-26 14:12
closing since there is no comment and the issue is probably fixed

**Closed as completed by nitaybz** 2019-11-26 14:12 UTC
