### ISSUE TITLE
HELLO!?!?

### ISSUE THREAD

**Issue by alexsalex** [nitaybz/homebridge-tado-ac#107] opened 2021-02-21 00:38 UTC
[2/20/2021, 4:36:17 PM] [homebridge-tado-ac] This plugin generated a warning from the characteristic 'Target Heating Cooling State': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.
[2/20/2021, 4:36:17 PM] [homebridge-tado-ac] This plugin generated a warning from the characteristic 'Target Heating Cooling State': characteristic was supplied illegal value: undefined! This might throw errors in the future! See https://git.io/JtMGR for more info.

**Comment by nitaybz** [comment] 2021-02-21 08:18
duplicate of #106 closing.... will be fixed in the next release

**Closed as completed by nitaybz** 2021-02-21 08:18 UTC
