### ISSUE TITLE
Crash when Tado AC is unit is offline

### ISSUE THREAD

**Issue by stbman** [nitaybz/homebridge-tado-ac#74] opened 2019-04-16 17:15 UTC
Hello!

I realize when a Tado AC unit is disconnected, this causes homebridge to crash during it boot sequence.
Was really hoping for a solution :S

im using
- homebridge-tado-ac version 3.1.2
- node 10.15.3
- homebridge 0.4.48

I am getting a mixture of this 2 error messages

TypeError: Cannot read property 'fanSpeeds' of undefined
at getMaxSpeed (/homebridge/node_modules/homebridge-tado-ac/index.js:549:44)
at TadoAccessory.getServices (/homebridge/node_modules/homebridge-tado-ac/index.js:556:52)
at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:427:36)
at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:413:32)
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
at async.waterfall (/homebridge/node_modules/homebridge-tado-ac/index.js:308:17)
at async.waterfall (/homebridge/node_modules/homebridge-tado-ac/index.js:294:24)
at fn (/homebridge/node_modules/async/lib/async.js:638:34)
at Immediate.<anonymous> (/homebridge/node_modules/async/lib/async.js:554:34)
at runCallback (timers.js:705:18)

TypeError: Cannot read property 'swings' of undefined
at TadoAccessory.getServices (/homebridge/node_modules/homebridge-tado-ac/index.js:539:69)
at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:427:36)
at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:413:32)
at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
at async.waterfall (/homebridge/node_modules/homebridge-tado-ac/index.js:308:17)
at async.waterfall (/homebridge/node_modules/homebridge-tado-ac/index.js:294:24)
at fn (/homebridge/node_modules/async/lib/async.js:638:34)
at Immediate.<anonymous> (/homebridge/node_modules/async/lib/async.js:554:34)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)

**Comment by nitaybz** [comment] 2019-10-06 08:41
this issue should already been fixed long time ago... sorry for not updating you.
please let me know if there are any more issues

**Comment by nitaybz** [comment] 2019-11-26 14:13
closing since there is no comment and the issue is probably fixed

**Closed as completed by nitaybz** 2019-11-26 14:13 UTC
