### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by nicktmro** [nitaybz/homebridge-tado-ac#66] opened 2019-02-07 21:26 UTC
Hi,

This crash brought down homebridge. Please let me know if I can help with the diagnose. 

I'm running:
```
 homebridge@0.4.45
 homebridge-tado-ac@3.1.2
```

Crash log:
```
[2/8/2019, 2:24:03 AM] [TadoAC] Living room Tado *New State* - Relative Humidity - 47.1 %
/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:223
                        if (state.setting.power !== 'OFF') {
                                         ^

TypeError: Cannot read property 'power' of undefined
    at tadoApi.getState (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoHelpers.js:223:42)
    at IncomingMessage.res.on.e (/usr/local/lib/node_modules/homebridge-tado-ac/lib/tadoApi.js:213:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Cheers

**Comment by nitaybz** [comment] 2019-10-06 10:15
Please try the latest version (3.2)... it should solve this issue

**Comment by nitaybz** [comment] 2019-11-26 14:12
closing since there is no comment and the issue is probably fixed

**Closed as completed by nitaybz** 2019-11-26 14:12 UTC
